name: 手动编译 .NET8 WinForms WebView2

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: NuGet 还原依赖
        run: dotnet restore

      - name: Release 编译
        run: dotnet build --configuration Release --no-restore

      - name: 发布框架依赖版本
        run: |
          dotnet publish `
          --configuration Release `
          --framework net8.0-windows `
          --self-contained false `
          --output ./publish/App

      - name: 上传编译成品
        uses: actions/upload-artifact@v4
        with:
          name: App-编译成品
          path: ./publish/App